### ISSUE TITLE
Support a way to group .anyOf() conditions

### ISSUE THREAD

**Issue by ealush** [fiverr/passable#20]
Currently we support these three main enforce conditionals:
`noneOf()`, `allOf()`, `anyOf()`.

With anyOf we can easily determine whether a single condition is true, so we can do things like:

- may either be a string or a number
```js
enforce(value).anyOf({
    isString: true,
    isNumber: true
});
```
- may be empty or larger than 55
```js
enforce(value).anyOf({
    isEmpty: true,
    largerThan: 55
});
```

But there is no straightforward way to test against groups of conditionals, for example:
- May be an array or a number smaller than 25

------
Initially I thought of the following syntax
```js
enforce(value).anyOf({
    isArray: true
}, {
    isNumber: true,
    smallerThan: 25
});
```

But I think it would be too confusing, as it is not inherently different than the normal way of doing it:
Do the internal conditionals (in each object) also go according to anyOf? Does it mean that it is actually going to run as: an array, or a number, or smaller than 25? or each of the objects work internally with `allOf`?

We could, of course, support this syntax, only by changing its name:
```js
enforce(value).anyGroup({
    isArray: true
}, {
    isNumber: true,
    smallerThan: 25
});
```
But it is not as self explanatory as the others.

----

I am currently leaning towards:
```js
enforce(value).anyOf([{
    isArray: true
}, {
    isNumber: true,
    smallerThan: 25
}]);
```
as it does add another layer on top of anyOf, hinting that the normal mode of operation does not apply here anymore.

**Comment by ronen-e** [comment]
You could just chain `anyOf` right?
```js
enforce(value)
.anyOf({
    isString: true,
    isNumber: true
})
.anyOf({
    isArray: true
});
```

You could also change the test runners to support arrays like this:
```js
enforce(value).anyOf([
{
    isString: true,
    isNumber: true
},
{
    isArray: true
}
]);
```

**Comment by ealush** [comment]
Hey @ronen-e , thanks for the reply :)

Chaining `.anyOf()` will not achieve the desired result, as it will internally evaluate each as a regular anyof. I am looking for sort of a mix between `allOf()` and `anyOf()` in which all members of at least one group need to be true - unlike `anyOf` in which only one member has to be true.

so it should be more like:
_EITHER_ `is array`, _OR_ `is a number AND larger than 25`
which currently can't be described just by chaining. When chaining, it would be:
`is array`, _AND_ `is a number OR larger than 25`

The array notation can be defined to describe it, but I am not sure it is self explanatory enough.

**Comment by ronen-e** [comment]
Another way of doing it would be to reuse test runners inside runners like calling `allOf` test runner on tests by `anyOf` runner:

```js
enforce(value).anyOf({
    allOf: {
        isNumber: true,
        smallerThan: 25
    },
    isArray: true,
});
```
This way is more self explanatory and does not require new test runners.
This means changing your test runners to enable them to run other runners like: 
__(Not production code)__

```js
// @flow
import run from '../run';
import allOf from '../all_of';
import noneOf from '../none_of';

const runners = {
    anyOf,
    allOf,
    noneOf
};

export default function anyOf(value: mixed, tests: Tests, rules: Rules): boolean {

    const validations: Array<string> = Object.keys(tests);
    return validations.some((key) => { 
        if (runners.hasOwnProperty(key)) {
            return runners[key](value, tests[key], rules);
        }
                            
        return run(value, key, tests, rules) === true);
    }
}

```

This will cover more complex use cases like nested groups:

```js
enforce(value).anyOf({
    allOf: {
        noneOf: { ... }
        isArray: true
    }
})
```

**Comment by ealush** [comment]
That's an interesting concept. I'll have to give it some thought.
It does seem to solve the issue, while providing even more flexibility and covering more cases than I tried to cover in this issue.
Great idea💡

**Comment by ealush** [comment]
After giving it some thought, I realized this solution prevents us from setting multiple groups. The following example could never work:
```js
enforce(data).anyOf({
    allOf: {
        isArray: true,
        largerThan: 5
    },
    allOf: {
        isString: true,
        matches: /hello/
    }
});
```

which leads me back to consider using an array for groups:
```js
enforce(data).anyOf([{
    isArray: true,
    largerThan: 5
}, {
    isString: true,
    matches: /hello/
}]);
```

Your suggested syntax could still be added (I still find it very useful), but not as a solution to this specific issue.

**Comment by ronen-e** [comment]
@ealush you are possibly overextending yourself trying to solve that specific use case.

Something like this is unlikely:
```js
enforce(data).anyOf({
    allOf: {
        isArray: true,
        largerThan: 5
    },
    allOf: {
        isString: true,
        matches: /hello/
    }
});
```

If the need does come up for something like the above example it would be better to use another `enforce` block or even `pass` block in conjunction with the `result` object.

I would wait and see if there is popular demand for solving such use cases as it seems to me you are moving away from the premise of the library being `like unit testing`, which for me was a rather good feature.

**Comment by ealush** [comment]
@ronen-e, I see your point there. While Passable tries to mimic the spirit and style of unit tests, there is still one large difference: Passable runs on production code, with unexpected data sets.

As such, Passable might sometimes need to expand to support use cases which are not necessarily supported in regular `expect` type tests. Grouping `anyOf` conditions could end up being one. For now I will close the issue, and resurface it if the need arises.

Thanks for your input.

**Comment by ronen-e** [comment]
I realize the issue is closed but I have some more input on the subject.

You can get around the issue of multiple keys with same value by using `Symbols` if you support them.

**Instead of:**
```js
enforce(data).anyOf({
    allOf: {
        isArray: true,
        largerThan: 5
    },
    allOf: {
        isString: true,
        matches: /hello/
    }
});
```
**You can do this:**
```js
enforce(data).anyOf({
    [Symbol('allOf')]: {
        isArray: true,
        largerThan: 5
    },
    [Symbol('allOf')]: {
        isString: true,
        matches: /hello/
    }
});
```

This would require minor changes for the code to run properly:
```js
// @flow
import run from '../run';
import allOf from '../all_of';
import noneOf from '../none_of';

const runners = {
    anyOf,
    allOf,
    noneOf
};

export default function anyOf(value: mixed, tests: Tests, rules: Rules): boolean {

    const validations: Array<string|symbol> = [...Object.getOwnPropertyNames(tests), ...Object.getOwnPropertySymbols(tests)];
    return validations.some((key) => { 
        let name = (typeof key === 'symbol') ? key.toString().replace(/Symbol\(|\)/g, '') : key;  
        if (runners.hasOwnProperty(name)) {
            return runners[key](value, tests[key], rules);
        }
                            
        return run(value, key, tests, rules) === true);
    }
}  
```
