### ISSUE TITLE
Scripts are not running in PR's Checks

### ISSUE THREAD

**Issue by Attrash-Islam** [fiverr/passable#285]
We need to run the scripts in PR's Checks and block PR unless all the checks pass.

![image](https://user-images.githubusercontent.com/7091543/82502435-c4f5c300-9aff-11ea-9e5b-e67e5f491573.png)

Currently, PR don't have such a checks!

![image](https://user-images.githubusercontent.com/7091543/82502330-911a9d80-9aff-11ea-8762-b8740cc1a54b.png)

.. And even when running lint locally there's a bunch of errors that we could prevented by blocking PRs:

![image](https://user-images.githubusercontent.com/7091543/82502481-e0f96480-9aff-11ea-823e-c81b5449401b.png)

**Comment by Attrash-Islam** [comment]
Want or do you've the time to have a look @ealush ?

**Comment by ealush** [comment]
Hm. Looks like stuff still run pretty well in ci. https://travis-ci.org/github/fiverr/passable

Things may have changed in the repo settings. Regarding the lint errors, they are there, but not blocking. You may ignore those.
![image](https://user-images.githubusercontent.com/11255103/82503001-1e122680-9b01-11ea-8f2f-542053f770bd.png)

**Comment by Attrash-Islam** [comment]
@sahariko Can you check the repository settings? I don't have permission for this

**Comment by Attrash-Islam** [comment]
Thanks @ealush ❤🌷

**Comment by Attrash-Islam** [comment]
@omrilotan This has been resolved. Right?

**Comment by omrilotan** [comment]
I don't know, is it running correctly now?

**Comment by Attrash-Islam** [comment]
I see more checks in your PR (4 whereas I got 2), not sure if it got fixed totally.
